language: php

# Use container-based infrastructure
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  
matrix:
  # For some reason Codeception fails without any output on PHP 7.0
  allow_failures:
    - php: 7.0

before_script:
  - composer install

script:
  - composer travis

after_success:
 - mkdir -p build/logs
 - cp tests/_output/coverage.xml build/logs/clover.xml
 - php vendor/bin/coveralls -v

