language: php

# Use container-based infrastructure

php:
  - 7.2
  - 7.3

before_script:
  - composer install

script:
  - composer travis

after_success:
 - mkdir -p build/logs
 - cp tests/_output/coverage.xml build/logs/clover.xml
 - php vendor/bin/coveralls -v
