language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - phpenv config-add tests/xdebug.ini
  - composer self-update
  - composer install --prefer-source

script: vendor/bin/codecept run unit

branches:
  only:
    - master
    - develop
